// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateUserDestroy.proto

package ssmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GateUserDestroy struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	GateUserID           *uint32  `protobuf:"varint,2,req,name=gateUserID" json:"gateUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateUserDestroy) Reset()         { *m = GateUserDestroy{} }
func (m *GateUserDestroy) String() string { return proto.CompactTextString(m) }
func (*GateUserDestroy) ProtoMessage()    {}
func (*GateUserDestroy) Descriptor() ([]byte, []int) {
	return fileDescriptor_23bd6e6973842938, []int{0}
}

func (m *GateUserDestroy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateUserDestroy.Unmarshal(m, b)
}
func (m *GateUserDestroy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateUserDestroy.Marshal(b, m, deterministic)
}
func (m *GateUserDestroy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateUserDestroy.Merge(m, src)
}
func (m *GateUserDestroy) XXX_Size() int {
	return xxx_messageInfo_GateUserDestroy.Size(m)
}
func (m *GateUserDestroy) XXX_DiscardUnknown() {
	xxx_messageInfo_GateUserDestroy.DiscardUnknown(m)
}

var xxx_messageInfo_GateUserDestroy proto.InternalMessageInfo

func (m *GateUserDestroy) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *GateUserDestroy) GetGateUserID() uint32 {
	if m != nil && m.GateUserID != nil {
		return *m.GateUserID
	}
	return 0
}

func init() {
	proto.RegisterType((*GateUserDestroy)(nil), "ssmessage.gateUserDestroy")
}

func init() { proto.RegisterFile("gateUserDestroy.proto", fileDescriptor_23bd6e6973842938) }

var fileDescriptor_23bd6e6973842938 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x4f, 0x2c, 0x49,
	0x0d, 0x2d, 0x4e, 0x2d, 0x72, 0x49, 0x2d, 0x2e, 0x29, 0xca, 0xaf, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x2c, 0x2e, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xf2, 0xe4, 0xe2,
	0x47, 0x53, 0x23, 0x24, 0xc6, 0xc5, 0x56, 0x5a, 0x9c, 0x5a, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0,
	0xa4, 0xc1, 0x19, 0x04, 0xe5, 0x09, 0xc9, 0x71, 0x71, 0xc1, 0x94, 0x7a, 0xba, 0x48, 0x30, 0x29,
	0x30, 0x69, 0xf0, 0x06, 0x21, 0x89, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x43, 0x6a, 0x25,
	0x6d, 0x00, 0x00, 0x00,
}
