// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kickGateUser.proto

package ssmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KickGateUser struct {
	UserID               *string  `protobuf:"bytes,1,req,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickGateUser) Reset()         { *m = KickGateUser{} }
func (m *KickGateUser) String() string { return proto.CompactTextString(m) }
func (*KickGateUser) ProtoMessage()    {}
func (*KickGateUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_0da6909f938651f8, []int{0}
}

func (m *KickGateUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickGateUser.Unmarshal(m, b)
}
func (m *KickGateUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickGateUser.Marshal(b, m, deterministic)
}
func (m *KickGateUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickGateUser.Merge(m, src)
}
func (m *KickGateUser) XXX_Size() int {
	return xxx_messageInfo_KickGateUser.Size(m)
}
func (m *KickGateUser) XXX_DiscardUnknown() {
	xxx_messageInfo_KickGateUser.DiscardUnknown(m)
}

var xxx_messageInfo_KickGateUser proto.InternalMessageInfo

func (m *KickGateUser) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*KickGateUser)(nil), "ssmessage.kickGateUser")
}

func init() { proto.RegisterFile("kickGateUser.proto", fileDescriptor_0da6909f938651f8) }

var fileDescriptor_0da6909f938651f8 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xce, 0x4c, 0xce,
	0x76, 0x4f, 0x2c, 0x49, 0x0d, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x2c, 0x2e, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52, 0xe3, 0xe2, 0x41, 0x56, 0x20,
	0x24, 0xc6, 0xc5, 0x56, 0x5a, 0x9c, 0x5a, 0xe4, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x19,
	0x04, 0xe5, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0xbd, 0x6b, 0x02, 0x47, 0x00, 0x00, 0x00,
}
