// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssToGate.proto

package ssmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SsToGate struct {
	GateUsers            []uint32 `protobuf:"varint,1,rep,name=gateUsers" json:"gateUsers,omitempty"`
	Message              [][]byte `protobuf:"bytes,2,rep,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SsToGate) Reset()         { *m = SsToGate{} }
func (m *SsToGate) String() string { return proto.CompactTextString(m) }
func (*SsToGate) ProtoMessage()    {}
func (*SsToGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_522604d763b2315a, []int{0}
}

func (m *SsToGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SsToGate.Unmarshal(m, b)
}
func (m *SsToGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SsToGate.Marshal(b, m, deterministic)
}
func (m *SsToGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SsToGate.Merge(m, src)
}
func (m *SsToGate) XXX_Size() int {
	return xxx_messageInfo_SsToGate.Size(m)
}
func (m *SsToGate) XXX_DiscardUnknown() {
	xxx_messageInfo_SsToGate.DiscardUnknown(m)
}

var xxx_messageInfo_SsToGate proto.InternalMessageInfo

func (m *SsToGate) GetGateUsers() []uint32 {
	if m != nil {
		return m.GateUsers
	}
	return nil
}

func (m *SsToGate) GetMessage() [][]byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*SsToGate)(nil), "ssmessage.ssToGate")
}

func init() { proto.RegisterFile("ssToGate.proto", fileDescriptor_522604d763b2315a) }

var fileDescriptor_522604d763b2315a = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x0e, 0xc9,
	0x77, 0x4f, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x2e, 0xce, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x72, 0xe2, 0xe2, 0x80, 0x49, 0x0a, 0xc9, 0x70, 0x71, 0xa6,
	0x27, 0x96, 0xa4, 0x86, 0x16, 0xa7, 0x16, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x06, 0x21,
	0x04, 0x84, 0x24, 0xb8, 0xd8, 0xa1, 0x9a, 0x24, 0x98, 0x14, 0x98, 0x35, 0x78, 0x82, 0x60, 0x5c,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xa7, 0xe6, 0x4d, 0x5f, 0x00, 0x00, 0x00,
}
