// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssToGateError.proto

package ssmessage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SsToGateError struct {
	Guid                 *uint32  `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SsToGateError) Reset()         { *m = SsToGateError{} }
func (m *SsToGateError) String() string { return proto.CompactTextString(m) }
func (*SsToGateError) ProtoMessage()    {}
func (*SsToGateError) Descriptor() ([]byte, []int) {
	return fileDescriptor_fceaff3e11737154, []int{0}
}

func (m *SsToGateError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SsToGateError.Unmarshal(m, b)
}
func (m *SsToGateError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SsToGateError.Marshal(b, m, deterministic)
}
func (m *SsToGateError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SsToGateError.Merge(m, src)
}
func (m *SsToGateError) XXX_Size() int {
	return xxx_messageInfo_SsToGateError.Size(m)
}
func (m *SsToGateError) XXX_DiscardUnknown() {
	xxx_messageInfo_SsToGateError.DiscardUnknown(m)
}

var xxx_messageInfo_SsToGateError proto.InternalMessageInfo

func (m *SsToGateError) GetGuid() uint32 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func init() {
	proto.RegisterType((*SsToGateError)(nil), "ssmessage.ssToGateError")
}

func init() { proto.RegisterFile("ssToGateError.proto", fileDescriptor_fceaff3e11737154) }

var fileDescriptor_fceaff3e11737154 = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x0e, 0xc9,
	0x77, 0x4f, 0x2c, 0x49, 0x75, 0x2d, 0x2a, 0xca, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x2c, 0x2e, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52, 0xe6, 0xe2, 0x45, 0x51,
	0x21, 0x24, 0xc4, 0xc5, 0x92, 0x5e, 0x9a, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1b, 0x04,
	0x66, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x8e, 0xc3, 0x43, 0x45, 0x00, 0x00, 0x00,
}
