// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Chat.proto

/*
Package testproto is a generated protocol buffer package.

It is generated from these files:
	Chat.proto

It has these top-level messages:
	ChatToS
	ChatToC
*/
package testproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatToS struct {
	Content          *string `protobuf:"bytes,1,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatToS) Reset()                    { *m = ChatToS{} }
func (m *ChatToS) String() string            { return proto.CompactTextString(m) }
func (*ChatToS) ProtoMessage()               {}
func (*ChatToS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatToS) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ChatToC struct {
	Response         *string `protobuf:"bytes,2,req,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatToC) Reset()                    { *m = ChatToC{} }
func (m *ChatToC) String() string            { return proto.CompactTextString(m) }
func (*ChatToC) ProtoMessage()               {}
func (*ChatToC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatToC) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatToS)(nil), "testproto.ChatToS")
	proto.RegisterType((*ChatToC)(nil), "testproto.ChatToC")
}

func init() { proto.RegisterFile("Chat.proto", fileDescriptor0) }

var fileDescriptor1 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x72, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x49, 0x2d, 0x2e, 0x01, 0x33, 0x95, 0xa4,
	0xb8, 0xd8, 0x41, 0x12, 0x21, 0xf9, 0xc1, 0x42, 0xfc, 0x5c, 0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9,
	0x79, 0x25, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x4a, 0xd2, 0x30, 0x39, 0x67, 0x21, 0x01, 0x2e,
	0x8e, 0xa2, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x09, 0x26, 0x90, 0x24, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x60, 0x32, 0x28, 0x63, 0x50, 0x00, 0x00, 0x00,
}
