// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/harbor.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotifyForginServicesH2SReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyForginServicesH2SReq) Reset()         { *m = NotifyForginServicesH2SReq{} }
func (m *NotifyForginServicesH2SReq) String() string { return proto.CompactTextString(m) }
func (*NotifyForginServicesH2SReq) ProtoMessage()    {}
func (*NotifyForginServicesH2SReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{0}
}

func (m *NotifyForginServicesH2SReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyForginServicesH2SReq.Unmarshal(m, b)
}
func (m *NotifyForginServicesH2SReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyForginServicesH2SReq.Marshal(b, m, deterministic)
}
func (m *NotifyForginServicesH2SReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyForginServicesH2SReq.Merge(m, src)
}
func (m *NotifyForginServicesH2SReq) XXX_Size() int {
	return xxx_messageInfo_NotifyForginServicesH2SReq.Size(m)
}
func (m *NotifyForginServicesH2SReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyForginServicesH2SReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyForginServicesH2SReq proto.InternalMessageInfo

func (m *NotifyForginServicesH2SReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NotifyForginServicesH2SResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyForginServicesH2SResp) Reset()         { *m = NotifyForginServicesH2SResp{} }
func (m *NotifyForginServicesH2SResp) String() string { return proto.CompactTextString(m) }
func (*NotifyForginServicesH2SResp) ProtoMessage()    {}
func (*NotifyForginServicesH2SResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{1}
}

func (m *NotifyForginServicesH2SResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyForginServicesH2SResp.Unmarshal(m, b)
}
func (m *NotifyForginServicesH2SResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyForginServicesH2SResp.Marshal(b, m, deterministic)
}
func (m *NotifyForginServicesH2SResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyForginServicesH2SResp.Merge(m, src)
}
func (m *NotifyForginServicesH2SResp) XXX_Size() int {
	return xxx_messageInfo_NotifyForginServicesH2SResp.Size(m)
}
func (m *NotifyForginServicesH2SResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyForginServicesH2SResp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyForginServicesH2SResp proto.InternalMessageInfo

type AddForginServicesH2SReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2SReq) Reset()         { *m = AddForginServicesH2SReq{} }
func (m *AddForginServicesH2SReq) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2SReq) ProtoMessage()    {}
func (*AddForginServicesH2SReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{2}
}

func (m *AddForginServicesH2SReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2SReq.Unmarshal(m, b)
}
func (m *AddForginServicesH2SReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2SReq.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2SReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2SReq.Merge(m, src)
}
func (m *AddForginServicesH2SReq) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2SReq.Size(m)
}
func (m *AddForginServicesH2SReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2SReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2SReq proto.InternalMessageInfo

func (m *AddForginServicesH2SReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AddForginServicesH2SResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2SResp) Reset()         { *m = AddForginServicesH2SResp{} }
func (m *AddForginServicesH2SResp) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2SResp) ProtoMessage()    {}
func (*AddForginServicesH2SResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{3}
}

func (m *AddForginServicesH2SResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2SResp.Unmarshal(m, b)
}
func (m *AddForginServicesH2SResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2SResp.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2SResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2SResp.Merge(m, src)
}
func (m *AddForginServicesH2SResp) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2SResp.Size(m)
}
func (m *AddForginServicesH2SResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2SResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2SResp proto.InternalMessageInfo

type RemForginServicesH2SReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2SReq) Reset()         { *m = RemForginServicesH2SReq{} }
func (m *RemForginServicesH2SReq) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2SReq) ProtoMessage()    {}
func (*RemForginServicesH2SReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{4}
}

func (m *RemForginServicesH2SReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2SReq.Unmarshal(m, b)
}
func (m *RemForginServicesH2SReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2SReq.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2SReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2SReq.Merge(m, src)
}
func (m *RemForginServicesH2SReq) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2SReq.Size(m)
}
func (m *RemForginServicesH2SReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2SReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2SReq proto.InternalMessageInfo

func (m *RemForginServicesH2SReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RemForginServicesH2SResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2SResp) Reset()         { *m = RemForginServicesH2SResp{} }
func (m *RemForginServicesH2SResp) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2SResp) ProtoMessage()    {}
func (*RemForginServicesH2SResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{5}
}

func (m *RemForginServicesH2SResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2SResp.Unmarshal(m, b)
}
func (m *RemForginServicesH2SResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2SResp.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2SResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2SResp.Merge(m, src)
}
func (m *RemForginServicesH2SResp) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2SResp.Size(m)
}
func (m *RemForginServicesH2SResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2SResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2SResp proto.InternalMessageInfo

//harbor之间发送
type NotifyForginServicesH2HReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyForginServicesH2HReq) Reset()         { *m = NotifyForginServicesH2HReq{} }
func (m *NotifyForginServicesH2HReq) String() string { return proto.CompactTextString(m) }
func (*NotifyForginServicesH2HReq) ProtoMessage()    {}
func (*NotifyForginServicesH2HReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{6}
}

func (m *NotifyForginServicesH2HReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyForginServicesH2HReq.Unmarshal(m, b)
}
func (m *NotifyForginServicesH2HReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyForginServicesH2HReq.Marshal(b, m, deterministic)
}
func (m *NotifyForginServicesH2HReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyForginServicesH2HReq.Merge(m, src)
}
func (m *NotifyForginServicesH2HReq) XXX_Size() int {
	return xxx_messageInfo_NotifyForginServicesH2HReq.Size(m)
}
func (m *NotifyForginServicesH2HReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyForginServicesH2HReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyForginServicesH2HReq proto.InternalMessageInfo

func (m *NotifyForginServicesH2HReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NotifyForginServicesH2HResp struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyForginServicesH2HResp) Reset()         { *m = NotifyForginServicesH2HResp{} }
func (m *NotifyForginServicesH2HResp) String() string { return proto.CompactTextString(m) }
func (*NotifyForginServicesH2HResp) ProtoMessage()    {}
func (*NotifyForginServicesH2HResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{7}
}

func (m *NotifyForginServicesH2HResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyForginServicesH2HResp.Unmarshal(m, b)
}
func (m *NotifyForginServicesH2HResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyForginServicesH2HResp.Marshal(b, m, deterministic)
}
func (m *NotifyForginServicesH2HResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyForginServicesH2HResp.Merge(m, src)
}
func (m *NotifyForginServicesH2HResp) XXX_Size() int {
	return xxx_messageInfo_NotifyForginServicesH2HResp.Size(m)
}
func (m *NotifyForginServicesH2HResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyForginServicesH2HResp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyForginServicesH2HResp proto.InternalMessageInfo

func (m *NotifyForginServicesH2HResp) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AddForginServicesH2HReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2HReq) Reset()         { *m = AddForginServicesH2HReq{} }
func (m *AddForginServicesH2HReq) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2HReq) ProtoMessage()    {}
func (*AddForginServicesH2HReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{8}
}

func (m *AddForginServicesH2HReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2HReq.Unmarshal(m, b)
}
func (m *AddForginServicesH2HReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2HReq.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2HReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2HReq.Merge(m, src)
}
func (m *AddForginServicesH2HReq) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2HReq.Size(m)
}
func (m *AddForginServicesH2HReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2HReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2HReq proto.InternalMessageInfo

func (m *AddForginServicesH2HReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type AddForginServicesH2HResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2HResp) Reset()         { *m = AddForginServicesH2HResp{} }
func (m *AddForginServicesH2HResp) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2HResp) ProtoMessage()    {}
func (*AddForginServicesH2HResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{9}
}

func (m *AddForginServicesH2HResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2HResp.Unmarshal(m, b)
}
func (m *AddForginServicesH2HResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2HResp.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2HResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2HResp.Merge(m, src)
}
func (m *AddForginServicesH2HResp) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2HResp.Size(m)
}
func (m *AddForginServicesH2HResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2HResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2HResp proto.InternalMessageInfo

type RemForginServicesH2HReq struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2HReq) Reset()         { *m = RemForginServicesH2HReq{} }
func (m *RemForginServicesH2HReq) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2HReq) ProtoMessage()    {}
func (*RemForginServicesH2HReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{10}
}

func (m *RemForginServicesH2HReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2HReq.Unmarshal(m, b)
}
func (m *RemForginServicesH2HReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2HReq.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2HReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2HReq.Merge(m, src)
}
func (m *RemForginServicesH2HReq) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2HReq.Size(m)
}
func (m *RemForginServicesH2HReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2HReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2HReq proto.InternalMessageInfo

func (m *RemForginServicesH2HReq) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RemForginServicesH2HResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2HResp) Reset()         { *m = RemForginServicesH2HResp{} }
func (m *RemForginServicesH2HResp) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2HResp) ProtoMessage()    {}
func (*RemForginServicesH2HResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9678a441ab154bb9, []int{11}
}

func (m *RemForginServicesH2HResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2HResp.Unmarshal(m, b)
}
func (m *RemForginServicesH2HResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2HResp.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2HResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2HResp.Merge(m, src)
}
func (m *RemForginServicesH2HResp) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2HResp.Size(m)
}
func (m *RemForginServicesH2HResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2HResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2HResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NotifyForginServicesH2SReq)(nil), "proto.notifyForginServicesH2S_req")
	proto.RegisterType((*NotifyForginServicesH2SResp)(nil), "proto.notifyForginServicesH2S_resp")
	proto.RegisterType((*AddForginServicesH2SReq)(nil), "proto.addForginServicesH2S_req")
	proto.RegisterType((*AddForginServicesH2SResp)(nil), "proto.addForginServicesH2S_resp")
	proto.RegisterType((*RemForginServicesH2SReq)(nil), "proto.remForginServicesH2S_req")
	proto.RegisterType((*RemForginServicesH2SResp)(nil), "proto.remForginServicesH2S_resp")
	proto.RegisterType((*NotifyForginServicesH2HReq)(nil), "proto.notifyForginServicesH2H_req")
	proto.RegisterType((*NotifyForginServicesH2HResp)(nil), "proto.notifyForginServicesH2H_resp")
	proto.RegisterType((*AddForginServicesH2HReq)(nil), "proto.addForginServicesH2H_req")
	proto.RegisterType((*AddForginServicesH2HResp)(nil), "proto.addForginServicesH2H_resp")
	proto.RegisterType((*RemForginServicesH2HReq)(nil), "proto.remForginServicesH2H_req")
	proto.RegisterType((*RemForginServicesH2HResp)(nil), "proto.remForginServicesH2H_resp")
}

func init() { proto.RegisterFile("proto/harbor.proto", fileDescriptor_9678a441ab154bb9) }

var fileDescriptor_9678a441ab154bb9 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x48, 0x2c, 0x4a, 0xca, 0x2f, 0xd2, 0x03, 0x73, 0x84, 0x58, 0xc1, 0x94, 0x92,
	0x31, 0x97, 0x74, 0x5e, 0x7e, 0x49, 0x66, 0x5a, 0xa5, 0x5b, 0x7e, 0x51, 0x7a, 0x66, 0x5e, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0x6a, 0xb1, 0x87, 0x51, 0x70, 0x7c, 0x51, 0x6a, 0xa1, 0x90, 0x08,
	0x17, 0x6b, 0x5e, 0x7e, 0x4a, 0x6a, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x6f, 0x10, 0x84, 0xa3,
	0x24, 0xc7, 0x25, 0x83, 0x5b, 0x53, 0x71, 0x81, 0x92, 0x01, 0x97, 0x44, 0x62, 0x4a, 0x0a, 0x29,
	0x26, 0x4a, 0x73, 0x49, 0xe2, 0xd0, 0x01, 0x31, 0xae, 0x28, 0x35, 0x97, 0x44, 0xe3, 0x70, 0xe8,
	0x28, 0x2e, 0xc0, 0xed, 0x65, 0x0f, 0x3c, 0x26, 0x9a, 0xe0, 0xf2, 0xb2, 0x07, 0xd8, 0x50, 0x1c,
	0xba, 0xb0, 0x07, 0x84, 0x07, 0xc9, 0x01, 0xe1, 0x81, 0x2f, 0x20, 0x3c, 0x48, 0x0e, 0x08, 0x88,
	0x71, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xf9, 0x2c, 0x59, 0x17, 0x02, 0x00, 0x00,
}
