// Code generated by protoc-gen-go. DO NOT EDIT.
// source: heartbeat.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Heartbeat struct {
	OriginSender         *uint32  `protobuf:"varint,1,opt,name=originSender" json:"originSender,omitempty"`
	Timestamp1           *int64   `protobuf:"varint,2,opt,name=timestamp1" json:"timestamp1,omitempty"`
	Timestamp2           *int64   `protobuf:"varint,3,opt,name=timestamp2" json:"timestamp2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c667767fb9826a9, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetOriginSender() uint32 {
	if m != nil && m.OriginSender != nil {
		return *m.OriginSender
	}
	return 0
}

func (m *Heartbeat) GetTimestamp1() int64 {
	if m != nil && m.Timestamp1 != nil {
		return *m.Timestamp1
	}
	return 0
}

func (m *Heartbeat) GetTimestamp2() int64 {
	if m != nil && m.Timestamp2 != nil {
		return *m.Timestamp2
	}
	return 0
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "message.heartbeat")
}

func init() { proto.RegisterFile("heartbeat.proto", fileDescriptor_3c667767fb9826a9) }

var fileDescriptor_3c667767fb9826a9 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4d, 0x2c,
	0x2a, 0x49, 0x4a, 0x4d, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xca, 0xe7, 0xe2, 0x84, 0xcb, 0x09, 0x29, 0x71, 0xf1, 0xe4, 0x17,
	0x65, 0xa6, 0x67, 0xe6, 0x05, 0xa7, 0xe6, 0xa5, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x06, 0xa1, 0x88, 0x09, 0xc9, 0x71, 0x71, 0x95, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16,
	0x18, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x89, 0xa0, 0xc8, 0x1b, 0x49, 0x30, 0xa3,
	0xc9, 0x1b, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x43, 0x3e, 0x6c, 0xa0, 0x8b, 0x00, 0x00, 0x00,
}
