// Code generated by protoc-gen-go. DO NOT EDIT.
// source: center.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	center.proto

It has these top-level messages:
	Login
	LoginFailed
	HeartbeatToCenter
	HeartbeatToNode
	NodeInfo
	NotifyNodeInfo
	NodeLose
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Login struct {
	Tt               *string `protobuf:"bytes,1,req,name=tt" json:"tt,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Login) GetTt() string {
	if m != nil && m.Tt != nil {
		return *m.Tt
	}
	return ""
}

func (m *Login) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Login) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type LoginFailed struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginFailed) Reset()                    { *m = LoginFailed{} }
func (m *LoginFailed) String() string            { return proto.CompactTextString(m) }
func (*LoginFailed) ProtoMessage()               {}
func (*LoginFailed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginFailed) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type HeartbeatToCenter struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatToCenter) Reset()                    { *m = HeartbeatToCenter{} }
func (m *HeartbeatToCenter) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatToCenter) ProtoMessage()               {}
func (*HeartbeatToCenter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeartbeatToCenter) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type HeartbeatToNode struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	TimestampBack    *int64 `protobuf:"varint,2,req,name=timestamp_back,json=timestampBack" json:"timestamp_back,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatToNode) Reset()                    { *m = HeartbeatToNode{} }
func (m *HeartbeatToNode) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatToNode) ProtoMessage()               {}
func (*HeartbeatToNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HeartbeatToNode) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *HeartbeatToNode) GetTimestampBack() int64 {
	if m != nil && m.TimestampBack != nil {
		return *m.TimestampBack
	}
	return 0
}

type NodeInfo struct {
	Tt               *string `protobuf:"bytes,1,req,name=tt" json:"tt,omitempty"`
	Ip               *string `protobuf:"bytes,2,req,name=ip" json:"ip,omitempty"`
	Port             *int32  `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeInfo) GetTt() string {
	if m != nil && m.Tt != nil {
		return *m.Tt
	}
	return ""
}

func (m *NodeInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *NodeInfo) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type NotifyNodeInfo struct {
	Nodes            []*NodeInfo `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NotifyNodeInfo) Reset()                    { *m = NotifyNodeInfo{} }
func (m *NotifyNodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NotifyNodeInfo) ProtoMessage()               {}
func (*NotifyNodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NotifyNodeInfo) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeLose struct {
	Nodes            []*NodeInfo `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NodeLose) Reset()                    { *m = NodeLose{} }
func (m *NodeLose) String() string            { return proto.CompactTextString(m) }
func (*NodeLose) ProtoMessage()               {}
func (*NodeLose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeLose) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Login)(nil), "protocol.login")
	proto.RegisterType((*LoginFailed)(nil), "protocol.loginFailed")
	proto.RegisterType((*HeartbeatToCenter)(nil), "protocol.heartbeatToCenter")
	proto.RegisterType((*HeartbeatToNode)(nil), "protocol.heartbeatToNode")
	proto.RegisterType((*NodeInfo)(nil), "protocol.nodeInfo")
	proto.RegisterType((*NotifyNodeInfo)(nil), "protocol.notifyNodeInfo")
	proto.RegisterType((*NodeLose)(nil), "protocol.nodeLose")
}

func init() { proto.RegisterFile("center.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xd9, 0xc4, 0xc2, 0xee, 0xac, 0x56, 0xcd, 0xa9, 0x07, 0xc1, 0x12, 0x10, 0x7a, 0x2a,
	0x28, 0x9e, 0x14, 0x3c, 0x28, 0x08, 0x82, 0xec, 0x21, 0x88, 0x57, 0xc9, 0xb6, 0xb3, 0x6b, 0xd8,
	0x36, 0x13, 0xda, 0xb9, 0xf8, 0xef, 0xa5, 0xa9, 0x5d, 0x3d, 0x89, 0x78, 0xca, 0xbc, 0x61, 0xbe,
	0x37, 0x2f, 0x03, 0x87, 0x15, 0x7a, 0xc6, 0xae, 0x0c, 0x1d, 0x31, 0xa9, 0x79, 0x7c, 0x2a, 0x6a,
	0xf4, 0x2d, 0x24, 0x0d, 0x6d, 0x9d, 0x57, 0x29, 0x08, 0xe6, 0x6c, 0x96, 0x8b, 0x62, 0x61, 0x04,
	0xf3, 0xa0, 0x5d, 0xc8, 0xc4, 0xa8, 0x5d, 0x50, 0x0a, 0x0e, 0x02, 0x75, 0x9c, 0xc9, 0x5c, 0x14,
	0x89, 0x89, 0xb5, 0x3e, 0x87, 0x65, 0x84, 0x1f, 0xad, 0x6b, 0xb0, 0x56, 0x27, 0x20, 0xdb, 0x7e,
	0xfb, 0xe5, 0x31, 0x94, 0xfa, 0x12, 0x4e, 0xdf, 0xd1, 0x76, 0xbc, 0x46, 0xcb, 0x2f, 0xf4, 0x10,
	0x23, 0xa8, 0x33, 0x58, 0xb0, 0x6b, 0xb1, 0x67, 0xdb, 0x86, 0x38, 0x2c, 0xcd, 0x77, 0x43, 0xbf,
	0xc2, 0xf1, 0x0f, 0x64, 0x45, 0x35, 0xfe, 0x0e, 0xa8, 0x0b, 0x48, 0xf7, 0xe2, 0x6d, 0x6d, 0xab,
	0x5d, 0x0c, 0x2d, 0xcd, 0xd1, 0xbe, 0x7b, 0x6f, 0xab, 0x9d, 0xbe, 0x83, 0xb9, 0xa7, 0x1a, 0x9f,
	0xfc, 0x86, 0xfe, 0xf5, 0xd7, 0x1b, 0x48, 0x3d, 0xb1, 0xdb, 0x7c, 0xac, 0x26, 0x97, 0x02, 0x92,
	0xc1, 0xb1, 0xcf, 0x66, 0xb9, 0x2c, 0x96, 0x57, 0xaa, 0x9c, 0x8e, 0x5a, 0x4e, 0x8b, 0xcc, 0x38,
	0xa0, 0xaf, 0xc7, 0xdd, 0xcf, 0xd4, 0xe3, 0xdf, 0xa9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x0b, 0x8e, 0x66, 0xb3, 0x01, 0x00, 0x00,
}
