// Code generated by protoc-gen-go. DO NOT EDIT.
// source: harbor.proto

package cluster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddForginServicesH2S struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2S) Reset()         { *m = AddForginServicesH2S{} }
func (m *AddForginServicesH2S) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2S) ProtoMessage()    {}
func (*AddForginServicesH2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40fcde6cab63c6, []int{0}
}

func (m *AddForginServicesH2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2S.Unmarshal(m, b)
}
func (m *AddForginServicesH2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2S.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2S.Merge(m, src)
}
func (m *AddForginServicesH2S) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2S.Size(m)
}
func (m *AddForginServicesH2S) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2S.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2S proto.InternalMessageInfo

func (m *AddForginServicesH2S) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RemForginServicesH2S struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2S) Reset()         { *m = RemForginServicesH2S{} }
func (m *RemForginServicesH2S) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2S) ProtoMessage()    {}
func (*RemForginServicesH2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40fcde6cab63c6, []int{1}
}

func (m *RemForginServicesH2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2S.Unmarshal(m, b)
}
func (m *RemForginServicesH2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2S.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2S.Merge(m, src)
}
func (m *RemForginServicesH2S) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2S.Size(m)
}
func (m *RemForginServicesH2S) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2S.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2S proto.InternalMessageInfo

func (m *RemForginServicesH2S) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

//harbor之间发送
type AddForginServicesH2H struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddForginServicesH2H) Reset()         { *m = AddForginServicesH2H{} }
func (m *AddForginServicesH2H) String() string { return proto.CompactTextString(m) }
func (*AddForginServicesH2H) ProtoMessage()    {}
func (*AddForginServicesH2H) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40fcde6cab63c6, []int{2}
}

func (m *AddForginServicesH2H) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddForginServicesH2H.Unmarshal(m, b)
}
func (m *AddForginServicesH2H) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddForginServicesH2H.Marshal(b, m, deterministic)
}
func (m *AddForginServicesH2H) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddForginServicesH2H.Merge(m, src)
}
func (m *AddForginServicesH2H) XXX_Size() int {
	return xxx_messageInfo_AddForginServicesH2H.Size(m)
}
func (m *AddForginServicesH2H) XXX_DiscardUnknown() {
	xxx_messageInfo_AddForginServicesH2H.DiscardUnknown(m)
}

var xxx_messageInfo_AddForginServicesH2H proto.InternalMessageInfo

func (m *AddForginServicesH2H) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RemForginServicesH2H struct {
	Nodes                []uint32 `protobuf:"varint,1,rep,name=nodes" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemForginServicesH2H) Reset()         { *m = RemForginServicesH2H{} }
func (m *RemForginServicesH2H) String() string { return proto.CompactTextString(m) }
func (*RemForginServicesH2H) ProtoMessage()    {}
func (*RemForginServicesH2H) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40fcde6cab63c6, []int{3}
}

func (m *RemForginServicesH2H) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemForginServicesH2H.Unmarshal(m, b)
}
func (m *RemForginServicesH2H) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemForginServicesH2H.Marshal(b, m, deterministic)
}
func (m *RemForginServicesH2H) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemForginServicesH2H.Merge(m, src)
}
func (m *RemForginServicesH2H) XXX_Size() int {
	return xxx_messageInfo_RemForginServicesH2H.Size(m)
}
func (m *RemForginServicesH2H) XXX_DiscardUnknown() {
	xxx_messageInfo_RemForginServicesH2H.DiscardUnknown(m)
}

var xxx_messageInfo_RemForginServicesH2H proto.InternalMessageInfo

func (m *RemForginServicesH2H) GetNodes() []uint32 {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*AddForginServicesH2S)(nil), "cluster.addForginServicesH2S")
	proto.RegisterType((*RemForginServicesH2S)(nil), "cluster.remForginServicesH2S")
	proto.RegisterType((*AddForginServicesH2H)(nil), "cluster.addForginServicesH2H")
	proto.RegisterType((*RemForginServicesH2H)(nil), "cluster.remForginServicesH2H")
}

func init() { proto.RegisterFile("harbor.proto", fileDescriptor_1b40fcde6cab63c6) }

var fileDescriptor_1b40fcde6cab63c6 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x2c, 0x4a,
	0xca, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49,
	0x2d, 0x52, 0xd2, 0xe1, 0x12, 0x49, 0x4c, 0x49, 0x71, 0xcb, 0x2f, 0x4a, 0xcf, 0xcc, 0x0b, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xf6, 0x30, 0x0a, 0x16, 0x12, 0xe1, 0x62, 0xcd, 0xcb, 0x4f,
	0x49, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0d, 0x82, 0x70, 0x40, 0xaa, 0x8b, 0x52, 0x73,
	0x49, 0x50, 0x8d, 0xc5, 0x6c, 0x0f, 0x92, 0xcc, 0xc6, 0xa1, 0x1a, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0x9f, 0xe5, 0x98, 0xcf, 0x00, 0x00, 0x00,
}
